with open('public/dashboard.html', 'r') as f:
    content = f.read()

# 1. Add Device Type Dropdown to Form
old_form = '<form id="addForm">'
new_form = '''<form id="addForm">
    <select id="deviceType" style="width:100%; padding:10px; margin-bottom:15px; border:1px solid #ccc; border-radius:5px; font-size:16px;">
        <option value="Laptop">💻 Laptop</option>
        <option value="Phone">📱 Phone</option>
    </select>'''
content = content.replace(old_form, new_form, 1)

# 2. Add deviceType to form submission data
old_data = """const data = {
        brand: document.getElementById('brand').value,"""
new_data = """const data = {
        deviceType: document.getElementById('deviceType').value,
        brand: document.getElementById('brand').value,"""
content = content.replace(old_data, new_data, 1)

# 3. Add "Type" header to table
content = content.replace('<th>Brand</th>', '<th>Type</th>\n              <th>Brand</th>', 1)

# 4. Update empty table colspan
content = content.replace('colspan="9"', 'colspan="10"', 1)

# 5. Add "Type" cell to table rows
old_row = '<td><strong>${l.brand||\'\'}</strong></td>'
new_row = '<td>${l.deviceType === \'Phone\' ? \'📱 Phone\' : \' Laptop\'}</td>\n            <td><strong>${l.brand||\'\'}</strong></td>'
content = content.replace(old_row, new_row, 1)

# 6. Add Police Report button next to Delete button
old_del = '<button class="btn-sm btn-del" onclick="deleteItem(\'${l._id}\')">🗑️</button>'
new_del = '''<button class="btn-sm" style="background:#2563eb; color:white; margin-right:5px;" onclick="generatePoliceReport('${l._id}')">📄 Report</button>
              <button class="btn-sm btn-del" onclick="deleteItem('${l._id}')">🗑️</button>'''
content = content.replace(old_del, new_del, 1)

# 7. Add the Police Report function safely at the end (using string concatenation to avoid script bugs)
js_func = """
    window.generatePoliceReport = (id) => {
      const l = laptops.find(x => String(x._id) === id);
      if(!l) return;
      const win = window.open('', '_blank');
      let html = '<html><head><title>Police Report</title><style>body{font-family:Arial,sans-serif;padding:30px;color:#111;}h1{color:#dc2626;border-bottom:2px solid #dc2626;padding-bottom:10px;}.info{margin:12px 0;font-size:16px;}strong{color:#333;}hr{margin:20px 0;}</style></head><body>';
      html += '<h1>🚨 STOLEN DEVICE POLICE REPORT</h1>';
      html += '<p><strong>Date Generated:</strong> ' + new Date().toLocaleString() + '</p><hr>';
      html += '<div class="info"><strong>Device Type:</strong> ' + (l.deviceType || 'Laptop') + '</div>';
      html += '<div class="info"><strong>Brand:</strong> ' + l.brand + '</div>';
      html += '<div class="info"><strong>Model:</strong> ' + l.model + '</div>';
      html += '<div class="info"><strong>Serial Number:</strong> ' + l.serial + '</div>';
      html += '<div class="info"><strong>OB Number:</strong> ' + (l.obNumber || 'Not provided') + '</div>';
      html += '<div class="info"><strong>Police Station:</strong> ' + (l.policeStation || 'Not provided') + '</div><hr>';
      html += '<h2>Tracking Information</h2>';
      html += '<div class="info"><strong>Last Seen:</strong> ' + (l.lastSeen ? new Date(l.lastSeen).toLocaleString() : 'Never') + '</div>';
      html += '<div class="info"><strong>Last IP Address:</strong> ' + (l.lastIpAddress || 'Unknown') + '</div>';
      html += '<div class="info"><strong>Last Location:</strong> ' + (l.lastLocation && l.lastLocation.city ? l.lastLocation.city + ', ' + l.lastLocation.country : 'Unknown') + '</div><br>';
      html += '<p style="font-size:14px;color:#666;"><em>This report was automatically generated by Laptop Tracker. Please present this document to your local law enforcement agency to assist in the recovery of your device.</em></p>';
      html += '<script>window.print();<\\/script></body></html>';
      win.document.write(html);
      win.document.close();
    };
"""

content = content.replace('</body>', js_func + '</body>', 1)

with open('public/dashboard.html', 'w') as f:
    f.write(content)

print("✅ All features added safely in one pass! Dashboard is intact.")
