with open('public/dashboard.html', 'r') as f:
    content = f.read()

old_func = """    function generatePoliceReport(id) {
      const l = laptops.find(x => String(x._id) === id);
      if(!l) return;
      const win = window.open('', '_blank');
      win.document.write(`
        <html><head><title>Police Report - ${l.brand} ${l.model}</title>
        <style>body{font-family:Arial, sans-serif; padding:30px; color:#111;} h1{color:#dc2626; border-bottom:2px solid #dc2626; padding-bottom:10px;} .info{margin:12px 0; font-size:16px;} strong{color:#333;} hr{margin:20px 0;}</style>
        </head><body>
        <h1>🚨 STOLEN DEVICE POLICE REPORT</h1>
        <p><strong>Date Generated:</strong> ${new Date().toLocaleString()}</p>
        <hr>
        <div class="info"><strong>Device Type:</strong> ${l.deviceType || 'Laptop'}</div>
        <div class="info"><strong>Brand:</strong> ${l.brand}</div>
        <div class="info"><strong>Model:</strong> ${l.model}</div>
        <div class="info"><strong>Serial Number:</strong> ${l.serial}</div>
        <div class="info"><strong>OB Number:</strong> ${l.obNumber || 'Not provided'}</div>
        <div class="info"><strong>Police Station:</strong> ${l.policeStation || 'Not provided'}</div>
        <hr>
        <h2>Tracking Information</h2>
        <div class="info"><strong>Last Seen:</strong> ${l.lastSeen ? new Date(l.lastSeen).toLocaleString() : 'Never'}</div>
        <div class="info"><strong>Last IP Address:</strong> ${l.lastIpAddress || 'Unknown'}</div>
        <div class="info"><strong>Last Location:</strong> ${l.lastLocation?.city ? l.lastLocation.city + ', ' + l.lastLocation.country : 'Unknown'}</div>
        <br>
        <p style="font-size:14px; color:#666;"><em>This report was automatically generated by Laptop Tracker. Please present this document to your local law enforcement agency to assist in the recovery of your device.</em></p>
        <script>window.onload = function() { window.print(); }</script>
        </body></html>
      `);
    }"""

new_func = """    function generatePoliceReport(id) {
      const l = laptops.find(x => String(x._id) === id);
      if(!l) return;
      const win = window.open('', '_blank');
      const htmlContent = '<html><head><title>Police Report - ' + l.brand + ' ' + l.model + '</title>' +
        '<style>body{font-family:Arial, sans-serif; padding:30px; color:#111;} h1{color:#dc2626; border-bottom:2px solid #dc2626; padding-bottom:10px;} .info{margin:12px 0; font-size:16px;} strong{color:#333;} hr{margin:20px 0;}</style>' +
        '</head><body>' +
        '<h1>🚨 STOLEN DEVICE POLICE REPORT</h1>' +
        '<p><strong>Date Generated:</strong> ' + new Date().toLocaleString() + '</p><hr>' +
        '<div class="info"><strong>Device Type:</strong> ' + (l.deviceType || 'Laptop') + '</div>' +
        '<div class="info"><strong>Brand:</strong> ' + l.brand + '</div>' +
        '<div class="info"><strong>Model:</strong> ' + l.model + '</div>' +
        '<div class="info"><strong>Serial Number:</strong> ' + l.serial + '</div>' +
        '<div class="info"><strong>OB Number:</strong> ' + (l.obNumber || 'Not provided') + '</div>' +
        '<div class="info"><strong>Police Station:</strong> ' + (l.policeStation || 'Not provided') + '</div><hr>' +
        '<h2>Tracking Information</h2>' +
        '<div class="info"><strong>Last Seen:</strong> ' + (l.lastSeen ? new Date(l.lastSeen).toLocaleString() : 'Never') + '</div>' +
        '<div class="info"><strong>Last IP Address:</strong> ' + (l.lastIpAddress || 'Unknown') + '</div>' +
        '<div class="info"><strong>Last Location:</strong> ' + (l.lastLocation && l.lastLocation.city ? l.lastLocation.city + ', ' + l.lastLocation.country : 'Unknown') + '</div><br>' +
        '<p style="font-size:14px; color:#666;"><em>This report was automatically generated by Laptop Tracker. Please present this document to your local law enforcement agency to assist in the recovery of your device.</em></p>' +
        '</body></html>';
      win.document.write(htmlContent);
      win.document.close();
      win.print();
    }"""

if old_func in content:
    content = content.replace(old_func, new_func)
    with open('public/dashboard.html', 'w') as f:
        f.write(content)
    print("✅ Fixed the </script> bug! Dashboard will load normally now.")
else:
    print("❌ Could not find the exact function. Run: sed -n '231,259p' public/dashboard.html and reply with output.")
